openapi: 3.0.0
info:
  version: '1.0.0'
  title: Authentication API Service
  description: >
    Authentication API Service provides a JWT HTTP-Only Cookie used by other services for Authentication as well as Authorization Access Control purposes.

servers:
  - url: 'https://localhost:3000'

paths:
  /auth:
    get:
      tags:
        - Service
      summary: Returns authentication (login)
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
    delete:
      tags:
        - Service
      summary: Returns deauthentication (logout)
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Logout'
  /auth/health:
    get:
      tags:
        - Service Health Check
      summary: Returns the health status of the service.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'

components:
  schemas:
    Login:
      title: Login
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: email@domain.com
        password: qwerty123
    Logout:
      title: Logout
      type: object
    Health:
      title: Health Check
      type: object
      properties:
        timestamp:
          type: integer
        message:
          type: string
        data:
          type: object
      example:
        timestamp: 1553284037677
        message: Ok
        data: {}
