FROM node:10.14.1-alpine
ADD . /code
WORKDIR /code
RUN npm install
RUN npm run build
CMD ["npm", "run", "service-variant"]

HEALTHCHECK --interval=20s CMD wget --no-check-certificate -qO- https://localhost:5001/variant/health
