version: '3.3'

services:
  memcached:
    image: "memcached"
    ports:
      - "11211:11211"
    networks:
      - clinnet
  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    image: localhost:5000/clin-proxy-api-auth-service
    depends_on:
      - memcached
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
    env_file:
      - .env

networks:
  clinnet:
  proxy:
    external: true
