version: '3.3'

services:
  patient:
    build:
      context: ./app
      dockerfile: Dockerfile-patient
    volumes:
      - ./app/src:/code/src
    ports:
      - "4000:4000"
    networks:
      - proxy
    env_file:
      - app/.env
    command: ["npm", "run", "dev-service-patient"]
  variant:
    build:
      context: ./app
      dockerfile: Dockerfile-variant
    volumes:
      - ./app/src:/code/src
    ports:
      - "5001:5001"
    networks:
      - proxy
    env_file:
      - app/.env
    command: ["npm", "run", "dev-service-variant"]
  meta:
    build:
      context: ./app
      dockerfile: Dockerfile-meta
    volumes:
      - ./app/src:/code/src
    ports:
      - "7000:7000"
    networks:
      - proxy
    env_file:
      - app/.env
    command: ["npm", "run", "dev-service-meta"]
  gene:
    build:
      context: ./app
      dockerfile: Dockerfile-gene
    volumes:
      - ./app/src:/code/src
    ports:
      - "5002:5002"
    networks:
      - proxy
    env_file:
      - app/.env
    command: ["npm", "run", "dev-service-gene"]

networks:
  proxy:
    external: true
