version: '3.3'

services:
  memcached:
    image: "memcached"
    ports:
      - "11211:11211"
    networks:
      - clinnet
  auth:
    image: localhost:5000/clin-proxy-api-auth-service
    volumes:
#      -for local dev only:
      - ./certificate-generation:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
#      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
    env_file:
      - auth.env
  patient:
    image: localhost:5000/clin-proxy-api-patient-service
    volumes:
#      --for local dev only:
      - ./certificate-generation:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
#      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "4000:4000"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
      - aidbox
    env_file:
      - patient.env
  variant:
    image: localhost:5000/clin-proxy-api-variant-service
    volumes:
#      --for local dev only:
      - ./certificate-generation:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
#      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
    env_file:
      - variant.env
  meta:
    image: localhost:5000/clin-proxy-api-meta-service
    volumes:
#      --for local dev only:
      - ./certificate-generation:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
#      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "7000:7000"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
    env_file:
      - meta.env

  gene:
    image: localhost:5000/clin-proxy-api-gene-service
    volumes:
      #      --for local dev only:
      - ./certificate-generation:/etc/letsencrypt
    #      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
    #      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "5002:5002"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
    env_file:
      - gene.env

networks:
  clinnet:
  proxy:
    external: true
  aidbox:
    external: true

#volumes:
#  sshvolume:
#    external: true
