FROM node:10.14.1-alpine
RUN apk add curl
ADD . /code
WORKDIR /code
RUN npm install
RUN npm run build
CMD ["npm", "run", "service-meta"]

HEALTHCHECK --interval=20s CMD curl -kf https://localhost:7000/meta/health

ENV MEMORY_LIMIT 256