version: '3.3'

services:
  memcached:
    image: "memcached"
    ports:
      - "11211:11211"
    networks:
      - clinnet
  auth:
    image: chusj/clin-proxy-api-auth-service:$DEFAULT_PROD_VERSION
    volumes:
#      -for local dev only:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
    networks:
      - clinnet
      - proxy
    env_file:
      - auth.env
  patient:
    image: chusj/clin-proxy-api-patient-service:$DEFAULT_PROD_VERSION
    volumes:
#      --for local dev only:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "4000:4000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
    networks:
      - clinnet
      - proxy
    env_file:
      - patient.env
  variant:
    image: chusj/clin-proxy-api-variant-service:$DEFAULT_PROD_VERSION
    volumes:
#      --for local dev only:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
    networks:
      - clinnet
      - proxy
    env_file:
      - variant.env
  meta:
    image: chusj/clin-proxy-api-meta-service:$DEFAULT_PROD_VERSION
    volumes:
      #      --for local dev only:
      #      - ./data/certbot/conf:/etc/letsencrypt
      #      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "7000:7000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
    networks:
      - clinnet
      - proxy
    env_file:
      - meta.env

  gene:
    image: chusj/clin-proxy-api-gene-service:$DEFAULT_PROD_VERSION
    volumes:
      #      --for local dev only:
      #      - ./data/certbot/conf:/etc/letsencrypt
      #      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    ports:
      - "5002:5002"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
    networks:
      - clinnet
      - proxy
    env_file:
      - gene.env


networks:
  clinnet:
    external: true
  proxy:
    external: true

volumes:
  sshvolume:
    external: true
