FROM jboss/keycloak:latest
RUN apk add curl
ADD ./clin-keycloak-theme /code
WORKDIR /code
RUN npm config set unsafe-perm true
RUN npm install
RUN npm install nodemon -g --save
RUN npm run build --ignore-scripts
CMD ["npm", "run", "service-gene"]

HEALTHCHECK --interval=20s CMD curl -kf https://localhost:5002/gene/health

ENV MEMORY_LIMIT 256
