version: '3.3'

services:
  memcached:
    image: "memcached"
    ports:
      - "11211:11211"
    networks:
      - clinnet
    deploy:
      mode: replicated
      #Given that memcached is a stateful application and this is not a cluster, keep this value at 1
      replicas: 1
      resources:
        limits:
          cpus: '2.00'
          memory: 256M
        reservations:
          cpus: '1.00'
          memory: 128M
    #https://docs.oracle.com/cd/E17952_01/mysql-5.1-en/ha-memcached-cmdline-options.html
    command: "memcached -m 128 -t 4"
  auth:
    image: localhost:5000/clin-proxy-api-auth-service
    volumes:
      - ./certificate-generation:/etc/letsencrypt
      - ./src:/code/src
    depends_on:
      - memcached
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - auth.env
    command: ["npm", "run", "dev-service-auth"]
  patient:
    image: localhost:5000/clin-proxy-api-patient-service
    volumes:
      - ./certificate-generation:/etc/letsencrypt
      - ./src:/code/src
    depends_on:
      - memcached
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
      - aidbox
    env_file:
      - patient.env
    command: ["npm", "run", "dev-service-patient"]
  variant:
    image: localhost:5000/clin-proxy-api-variant-service
    volumes:
      - ./certificate-generation:/etc/letsencrypt
      - ./src:/code/src
    depends_on:
      - memcached
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M
    networks:
      - clinnet
      - proxy
    env_file:
      - variant.env
    command: ["npm", "run", "dev-service-variant"]
  meta:
    image: localhost:5000/clin-proxy-api-meta-service
    volumes:
      - ./certificate-generation:/etc/letsencrypt
      - ./src:/code/src
    depends_on:
      - memcached
    ports:
      - "7000:7000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - meta.env
    command: ["npm", "run", "dev-service-meta"]
  gene:
    image: localhost:5000/clin-proxy-api-gene-service
    volumes:
      - ./certificate-generation:/etc/letsencrypt
      - ./src:/code/src
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - gene.env
    command: ["npm", "run", "dev-service-gene"]

networks:
  clinnet:
    external: true
  proxy:
    external: true
  aidbox:
    external: true
