FROM node:10.14.1-alpine
RUN apk add curl
ADD . /code
WORKDIR /code
RUN npm config set unsafe-perm true
RUN npm install
RUN npm install nodemon -g --save
RUN npm run build --ignore-scripts
CMD ["npm", "run", "service-patient"]

HEALTHCHECK --interval=20s CMD curl -kf https://localhost:4000/patient/health

ENV MEMORY_LIMIT 256
