version: '3.3'

services:
  memcached:
    image: "memcached"
    ports:
      - "11211:11211"
    networks:
      - clinnet
  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    image: localhost:5000/clin-proxy-api-auth-service
    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt  -- for local
      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
    depends_on:
      - memcached
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
    env_file:
      - auth.env
  patient:
    build:
      context: .
      dockerfile: Dockerfile-patient
    image: localhost:5000/clin-proxy-api-patient-service
    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt  --for local usage
      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
    depends_on:
      - memcached
    ports:
      - "4000:4000"
    deploy:
      replicas: 2
    networks:
      - clinnet
      - proxy
    env_file:
      - patient.env

networks:
  clinnet:
  proxy:
    external: true
