version: '3.3'

services:
  memcached:
    image: "memcached"
    ports:
      - "11211:11211"
    networks:
      - clinnet
    deploy:
      mode: replicated
      #Given that memcached is a stateful application and this is not a cluster, keep this value at 1
      replicas: 1
      resources:
        limits:
          cpus: '2.00'
          memory: 256M
        reservations:
          cpus: '1.00'
          memory: 128M
    #https://docs.oracle.com/cd/E17952_01/mysql-5.1-en/ha-memcached-cmdline-options.html
    command: "memcached -m 128 -t 4"
  auth:
    image: chusj/clin-proxy-api-auth-service:$DEFAULT_PROD_VERSION
    volumes:
#      -for local dev only:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - auth.env
  patient:
    image: chusj/clin-proxy-api-patient-service:$DEFAULT_PROD_VERSION
    volumes:
#      --for local dev only:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "4000:4000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - aidbox
      - clinnet
      - proxy
    env_file:
      - patient.env
  variant:
    image: chusj/clin-proxy-api-variant-service:$DEFAULT_PROD_VERSION
    volumes:
#      --for local dev only:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - variant.env
  meta:
    image: chusj/clin-proxy-api-meta-service:$DEFAULT_PROD_VERSION
    volumes:
      #      --for local dev only:
      #      - ./data/certbot/conf:/etc/letsencrypt
      #      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    depends_on:
      - memcached
    ports:
      - "7000:7000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - meta.env

  gene:
    image: chusj/clin-proxy-api-gene-service:$DEFAULT_PROD_VERSION
    volumes:
      #      --for local dev only:
      #      - ./data/certbot/conf:/etc/letsencrypt
      #      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    ports:
      - "5002:5002"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.node_role == devops]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - gene.env


networks:
  aidbox:
    external: true
  clinnet:
    external: true
  proxy:
    external: true

volumes:
  sshvolume:
    external: true
