FROM node:10.14.1-alpine
RUN apk add curl
ADD . /code
WORKDIR /code
RUN npm config set unsafe-perm true
RUN npm install
RUN npm install nodemon -g --save
RUN npm run build
CMD ["npm", "run", "service-hpo"]

HEALTHCHECK --interval=20s CMD curl -kf http://localhost:8400/hpo/health

ENV MEMORY_LIMIT 256
