---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clin-proxy-api-meta
  name: clin-proxy-api-meta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clin-proxy-api-meta
  template:
    metadata:
      labels:
        app: clin-proxy-api-meta
    spec:
      containers:
        - image: chusj/clin-proxy-api-meta-service:__UNDEFINED__
          name: clin-proxy-api-meta
          resources:
            requests:
              memory: "128Mi"
              cpu: '0.25'
            limits:
              memory: "256Mi"
              cpu: '0.50'
          envFrom:
            - configMapRef:
                name: clin-proxy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clin-proxy-api-gene
  name: clin-proxy-api-gene
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clin-proxy-api-gene
  template:
    metadata:
      labels:
        app: clin-proxy-api-gene
    spec:
      containers:
        - image: chusj/clin-proxy-api-gene-service:__UNDEFINED__
          name: clin-proxy-api-gene
          resources:
            requests:
              memory: "128Mi"
              cpu: '0.25'
            limits:
              memory: "256Mi"
              cpu: '0.50'
          envFrom:
            - configMapRef:
                name: clin-proxy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clin-proxy-api-variant
  name: clin-proxy-api-variant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clin-proxy-api-variant
  template:
    metadata:
      labels:
        app: clin-proxy-api-variant
    spec:
      containers:
        - image: chusj/clin-proxy-api-variant-service:__UNDEFINED__
          name: clin-proxy-api-variant
          resources:
            requests:
              memory: "128Mi"
              cpu: '0.25'
            limits:
              memory: "256Mi"
              cpu: '0.50'
          envFrom:
            - configMapRef:
                name: clin-proxy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clin-proxy-api-patient
  name: clin-proxy-api-patient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clin-proxy-api-patient
  template:
    metadata:
      labels:
        app: clin-proxy-api-patient
    spec:
      containers:
        - image: chusj/clin-proxy-api-patient-service:__UNDEFINED__
          name: clin-proxy-api-patient
          resources:
            requests:
              memory: "128Mi"
              cpu: '0.25'
            limits:
              memory: "256Mi"
              cpu: '0.50'
          envFrom:
            - configMapRef:
                name: clin-proxy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clin-proxy-api-hpo
  name: clin-proxy-api-hpo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clin-proxy-api-hpo
  template:
    metadata:
      labels:
        app: clin-proxy-api-hpo
    spec:
      containers:
        - image: chusj/clin-proxy-api-hpo-service:__UNDEFINED__
          name: clin-proxy-api-hpo
          resources:
            requests:
              memory: "128Mi"
              cpu: '0.25'
            limits:
              memory: "256Mi"
              cpu: '0.50'
          envFrom:
            - configMapRef:
                name: clin-proxy-config