---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clin-proxy-config
data:
  KEYCLOAK_CONFIG: |
    { "realm": "clin", "authServerUrl": "https://auth.qa.cqdg.ferlab.bio" }
  ELASTIC_SERVICE: |
    {"host": "http://elasticsearch-workers:9200"}
  VARIANT_API_SERVICE: |
    {"name": "Variant", "endpoint": "/variant", "port": 5001, "defaultVersion": 1, "availableVersions": [1], "schemaVariables": { "GENE_API_SEARCH_ENDPOINT": "https://gene.qa.clin.ferlab.bio/autocomplete"}}