---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common
  - ingresses.yml

patchesStrategicMerge:
  - configmaps.yml
  - deployments.yml

commonLabels:
  group: clin-proxy-api