#https://github.com/Magnitus-/DockerFiles/blob/master/certificate/example/ca-signed/docker-compose.yml
version: "3"
services:
    ca-certificate-generator:
        image: magnitus/certificate-generator:latest
        environment:
            COUNTRY: CA
            STATE: Quebec
            CITY: Montreal
            ORGANIZATION: Any
            DEPARTMENT: IT
            EMAIL: donttry@localhost.com
            DOMAINS: ca.chusj-clin-dev.org
            CERTIFICATE_DURATION: 1095
            KEY_FILE: "ca.key"
            CSR_FILE: "ca.csr"
            CERTIFICATE_FILE: "ca.crt"
            OUTPUT_CERTIFICATE_INFO: "true"
        volumes:
            - .:/opt/output
    certificate-generator:
        image: magnitus/certificate-generator:latest
        environment:
            COUNTRY: CA
            STATE: Quebec
            CITY: Montreal
            ORGANIZATION: Any
            DEPARTMENT: IT
            EMAIL: donttry@localhost.com
            DOMAINS: localhost;dev.chusj-clin-dev.org
            CERTIFICATE_DURATION: 1095
            KEY_FILE: "certificate.key"
            CSR_FILE: "certificate.csr"
            CERTIFICATE_FILE: "certificate.crt"
            CA_KEY_FILE: "/opt/output/ca.key"
            CA_CERTIFICATE_FILE: "/opt/output/ca.crt"
            OUTPUT_CERTIFICATE_INFO: "true"
        volumes:
            - .:/opt/output