name: Build Images

on: [push]

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        service: [patient, meta, variant, gene, hpo]
    steps:
    - uses: actions/checkout@v2
    - name: Ensure we can build the ${{ matrix.service }} service
      run: docker build -t test:test -f app/Dockerfile-${{ matrix.service }} app