name: Build Images

on:
  push:
    paths:
      - 'app/**'
      - .github/workflows/build_images.yml

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Ensure we can build the patient service
      run: docker build -t test:test -f app/Dockerfile-patient app
    - name: Ensure we can build the meta service
      run: docker build -t test:test -f app/Dockerfile-meta app
    - name: Ensure we can build the variant service
      run: docker build -t test:test -f app/Dockerfile-variant app
    - name: Ensure we can build the gene service
      run: docker build -t test:test -f app/Dockerfile-gene app