name: Functional Tests

on: [push]

jobs:
  build:
    name: Functional Tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
      working-directory: app
    - name: Run functional tests
      run: npm run functional-tests
      working-directory: app