name: Publish Images Using Commit Hash

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Images
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        service: [patient, meta, variant, gene]
    steps:
    - uses: actions/checkout@v2
    - name: Push the image on the ${{ matrix.service }} image on the registry
      uses: Ferlab-Ste-Justine/action-push-image@master
      with:
        username: chusj
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        image: chusj/clin-proxy-api-${{ matrix.service }}-service
        tag_source: sha
        location: .
        dockerfile: Dockerfile-${{ matrix.service }}