name: Unit Tests

on: [push]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
      working-directory: app
    - name: Run unit tests
      run: npm run unit-tests
      working-directory: app